name: packer

on:
  push:

env:
  PRODUCT_VERSION: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Build golden-grafana
    steps:
      - name: Debug - Show Current Directory
        run: pwd && ls -la

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ./build/packer/golden-grafana/ubuntu-server-jammy.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate -var-file=./build/packer/golden-grafana/variables.pkr.hcl ./build/packer/golden-grafana/variables.pkr.hcl"

      - name: run `packer build`
        id: build
        run: "packer build -var-file=./build/packer/golden-grafana/variables.pkr.hcl ./build/packer/golden-grafana/variables.pkr.hcl"
