name: packer

on:
  push:

env:
  PRODUCT_VERSION: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Build golden-grafana
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ./build/golden-grafan/ubuntu-server-jammy.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./build/golden-grafan/ubuntu-server-jammy.pkr.hcl"

      - name: run `packer build`
        id: build
        run: "packer build ./build/golden-grafana/ubuntu-server-jammy.pkr.hcl"




