name: packer

on:
  push:

env:
  PRODUCT_VERSION: "latest"

jobs:
  packer:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    name: Build golden-grafana
    environment: dev
    steps:
      - name: Debug - Show Current Directory
        run: pwd && ls -la

      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ./build/packer/golden-grafana/ubuntu-server-jammy.pkr.hcl"

      - name: Validate build
        run: |
          echo "Validating packer build"
          pwd && ls -la
          cd Chaos-labs/build/packer/golden-grafana
          packer validate .

      - name: Build image
        id: build
        run: |
          echo "Building packer image"
          packer build .
